### ISSUE TITLE
Teams do not sync

### ISSUE THREAD

**Issue by Paul19988** [PureGero/MultiPaper#105]
Vanilla teams do not sync between servers.

Replication steps:
 - /team add <name>
 - /team join <name> <player>
 - /team list (both servers)

The server which created the team will show it in the list but the other will not.

**Comment by PureGero** [comment]
Syncing teams should be an optional setting

**Comment by PureGero** [comment]
NametagEdit uses its own packets instead of using the Bukkit Teams API unfortunately.
