### ISSUE TITLE
Synced-Plugins

### ISSUE THREAD

**Issue by ezekielpari** [PureGero/MultiPaper#121]
Add directory to multipaper-master called Synced-Plugins
Multipaper, like Paper, and other server jars, should read plugins in this directory and set them up as per usual ... (Generation of config files etc)
And then it should sync it into all mp servers.

**Comment by PureGero** [comment]
This can be achieved by adding the plugin jar to the `synched-server-files/plugins` directory under master (you may need to create this directory), and adding the plugin data folder under `filesToSyncOnStartup` in multipaper.yml.

Eg, for a plugin MyPlugin.jar, you can do:
1. Move MyPlugin.jar to synched-server-files/plugins/MyPlugin.jar on the master
2. Add plugins/MyPlugin to filesToSyncOnStartup as such:
```yml
filesToSyncOnStartup:
- plugins/MyPlugin
```
3. Start the servers, and the config file will be generated and automatically uploaded to synched-server-files/plugins/MyPlugin/config.yml

**Comment by dalicor** [comment]
It doesn't make sense that a universally synced plugin, starts in 1 server.
It should at least be a central location ...Like master.

**Comment by TypicalShavonne** [comment]
isnt it already a feature ? https://github.com/PureGero/MultiPaper/issues/98

**Comment by dalicor** [comment]
> isnt it already a feature ? #98

Yes.

However it requires the manual creation of a sync folder and master does not generate the config contents of the jar.

Read the suggestion.
