### ISSUE TITLE
Chunk item duplication is possible

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#123]
1. Fill a chunk with things to duplicate.
2. Log out and wait a minute for a chunk to save.
3. Log back in and move things to a neighboring chunk. Put 20 140kB books into the duplicated chunk.
4. Log out and log back in after a minute - the chunk will revert with things inside.

MultiPaper doesn't support .mcc files which store chunks too big to fit into .mca.
Thus after overloading it with books, it's never saved and reverts.

**Comment by TypicalShavonne** [comment]
classic book duping
