### ISSUE TITLE
NBT on signs not working

### ISSUE THREAD

**Issue by ThatProgrammerr** [PureGero/MultiPaper#124]
Steps to reproduce;
1. Place Sign
2. Write something on it
3. Hold CTRL + Middle Click while looking at the sign you want to copy
4. With the new NBT sign, place it.

It would normally place the sign with the data on the sign you copied but instead brings up the new sign UI, as if it's ignoring the NBT. I've already checked chests and NBT works there, so it's likely just signs.

Video: https://cdn.thatprogrammer.dev/iaKnCvcsOF.mp4

**Comment by PureGero** [comment]
This is likely a more general Creative nbt copy not working, rather than just signs.

**Comment by ThatProgrammerr** [comment]
Yeah, I just know chests work, so I assumed it was just signs. Haha

**Comment by PureGero** [comment]
Appears to be resolved in 1.19
