### ISSUE TITLE
Blocks aren't synced + Errors with entities

### ISSUE THREAD

**Issue by imBuzz** [PureGero/MultiPaper#125]
Hi! Today I downloaded MultiPaper, i setupped it but i tried it with some friends and I noticed that blocks aren synced, for example if I place a block on server A, X on server B won't see it, but we will see the block place animation.

And about the entities their pathfinder is broken, for example a zombie when is on fire running at speed 1000 everywhere

**Comment by ThatProgrammerr** [comment]
I've just done these tests and couldn't reproduce this issue. What configuration of MultiPaper Servers are you using and what build number are you on?

**Comment by xymb-endcrystalme** [comment]
I had that problem when the names of both servers were the same.

@imBuzz Are you sure all your servers have unique names in `multipaper.yml`?

**Comment by HetMasterTje** [comment]
> Oh thank you! It fixed that
> 
> I have another question, is multipaper compatible with Velocity ?

You can use Velocity by just turning Velocity in the config on it works like normal

**Comment by imBuzz** [comment]
Perfect! And also is there a way to syncronize the entire plugins folder on the Master folder?

**Comment by imBuzz** [comment]
I don't understand, how can i share plugins folder? At the moment I have a folder on master folder called "synched-server-files" in which is a folder called "plugins" where i have all my plugins.

How can I tell to Multipaper to share every file of this folder on every slave server?

**Comment by ThatProgrammerr** [comment]
The 'synched-server-files' acts like a CDN that is downloaded from on every server boot. Anything you put in that folder will be downloaded to each server. The multipaper.yml file just allows you to select certain servers to sync those files on startup, shutdown or on file change.

**Comment by imBuzz** [comment]
Hi @ThatProgrammerr at the moment this is my multipaper.yml on my instance.
And on the master on synched-server-files/plugins there's a file called Basement-Bukkit-1.0.jar
But when i start the instance it isn't present on plugins' folder.

![image](https://user-images.githubusercontent.com/79755513/159520456-33187576-4e45-492c-85a3-3736319066d3.png)

**Comment by ThatProgrammerr** [comment]
Your slave servers will only download cached files on the master on server start. That config is only telling that server to upload that file to the master when it starts.

**Comment by ThatProgrammerr** [comment]
Happy to help.
