### ISSUE TITLE
Alert when two servers with the same name connect

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#127]
As evidenced here: https://github.com/PureGero/MultiPaper/issues/125

Two servers experience problems when their name is the same. MultiPaper Master should shout a loud warning on the console that the configuration is broken.
It's way too easy to do it by accident.

**Comment by ThatProgrammerr** [comment]
+1 I think this is 100% needed. As unlikely it is to do this with the autogenerated server names, it's still something that the master should disallow from happening and reject the connection, making the issue more obvious and getting it resolved quickly on the users' end.
