### ISSUE TITLE
Chunk ban with chunks bigger than 2MB

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#128]
1) Create a chunk > 2MB loaded on one subserver. For example a chest with 16 * 140kB books. Keep the chunk loaded with a player.
2) Take a second player (on a different subserver) and load the chunk.

The player will crash. The subserver will keep complaining about not getting a chunk:
```
[03:08:21 WARN]: [MultiPaperIO] Timed out reading world,region,1249,624, retrying...
[03:08:21 WARN]: [ExternalServerConnection] A chunk callback already existed for world, 1249, 624 (new request is to server15088)
[03:08:21 WARN]: [ExternalServerConnection] Stats for server15088: last packet sent=160ms ago; last packet received=85ms ago
```

And on a login the client will be stuck at `Loading terrain`.

**Comment by xymb-endcrystalme** [comment]
Pretty sure I found the problem.
```
      channel.pipeline()
              .addLast("splitter", new Varint21FrameDecoder())
              .addLast("decoder", new ExternalServerPacketDecoder())
              .addLast("prepender", new Varint21LengthFieldPrepender())
              .addLast("encoder", new ExternalServerPacketEncoder())
              .addLast("packet_handler", new ExternalServerPacketHandler(this));
```
MultiPaper is using vanilla Minecraft's packet handling which limits the fields to 21 bits = 2MB.

**Comment by emielderckx** [comment]
#123

**Comment by xymb-endcrystalme** [comment]
@emielderckx Unrelated. This one is because of subserver<->subserver communication.
