### ISSUE TITLE
Error when loading section [x,y,z]: Unknown registry key

### ISSUE THREAD

**Issue by fendyk** [PureGero/MultiPaper#137]
I added a custom datapack into the world, but when multipaper tries to load the chunks, it gives me the following error:

`[10:46:01 ERROR]: Recoverable errors when loading section [19, 11, -14]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: terralith:yosemite_lowlands -> using default)`

Example of my console (not the proxy, but from the server instance)
![afbeelding](https://user-images.githubusercontent.com/56702979/162951407-b33918c8-d57c-4b90-8396-22c45d35b174.png)

This error spams the console with each chunk load/update/sync. I might found a thread where the issue is located.
https://www.spigotmc.org/threads/unknown-registry-element-for-resourcekey-nms.548320/

**Disclaimer**
I tested the world and preloaded with chunky.

**Comment by xymb-endcrystalme** [comment]
`terralith:yosemite_lowlands`

That's a mod pack? Your configuration isn't default, right?

Can you post what exactly is your configuration? Without this we can't reproduce the problem.

**Comment by PureGero** [comment]
#96 might be related. Place the datapack into the world/datapacks folder on each server individually, not on master.

**Comment by fendyk** [comment]
@xymb-endcrystalme I only used a datapack inside of the worldfolder and what @PureGero pointed out didn't work for me however, I did fixed it using the Iris world engine.

Thanks for the help.
