### ISSUE TITLE
Multiserver

### ISSUE THREAD

**Issue by Lexivale** [PureGero/MultiPaper#14]
is multipaper master doesnt work with another server? i mean its like

- Survival I -> MultiPaper
- Survival II -> MultiPaper
- Survival III -> MultiPaper
- Skyblock -> Paper

because when i try to join Survival I and player disconnected from proxy. I'm using multipaper plugins bungeecord for teleporter suite

**Comment by PureGero** [comment]
I'm in the process of significantly changing how MultiPaper works with 1.18, so I'll close this issue for now
