### ISSUE TITLE
Velocity incompatible with MP 1.18.2-7

### ISSUE THREAD

**Issue by zekepari** [PureGero/MultiPaper#142]
Velocity does not recognise multipaper as a 1.18.2 instance.
![9ba4bd67588397e51fe7ff9a1b5daf8d](https://user-images.githubusercontent.com/68903556/163712260-b787ed81-974a-4026-806e-03f9e276676d.png)
Using Velocity-98 w MultiPaper 1.18.2-7

**Comment by PureGero** [comment]
What version of velocity are you using?

**Comment by zekepari** [comment]
> What version of velocity are you using?

Latest stable build (98 as mentioned)

**Comment by PureGero** [comment]
Velocity support for 1.18.2 was only added in build 115. Download it from https://papermc.io/downloads#Velocity
