### ISSUE TITLE
Unable to connect to another server to master

### ISSUE THREAD

**Issue by dandanlong123** [PureGero/MultiPaper#144]
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /43.248.96.220:8715
[10:59:09 WARN]: Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
[10:59:09 WARN]:        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
[10:59:09 WARN]:        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
[10:59:09 WARN]:        at io.netty.channel.unix.Socket.finishConnect(Socket.java:320)
[10:59:09 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
[10:59:09 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
[10:59:09 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
[10:59:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
[10:59:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[10:59:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[10:59:09 WARN]:        at

**Comment by dandanlong123** [comment]
There has been no way to link two at the same time. When I link the second one, the warning will be displayed on the first server. Cause collapse

**Comment by xymb-endcrystalme** [comment]
What's your exact configuration? Because that's where I suspect the problem lies.

Please post your `multipaper.yml` for both servers and complete logs from both servers and master.

**Comment by dandanlong123** [comment]
好的稍等一下

**Comment by dandanlong123** [comment]
# This is the main configuration file for MultiPaper.
# There's quite alot to configure. Read the docs for more information.
#
# Docs: https://github.com/PureGero/MultiPaper/blob/main/MULTIPAPER_YAML.md 

bungeecordName: server01172
multipaperMasterAddress: localhost:8051
syncJsonFiles: true
advertiseToBuiltInProxy: true
syncScoreboards: true
logFileSyncing: true
filesToSyncOnStartup:
- myconfigfile.yml
- plugins/MyPlugin.jar
filesToSyncInRealTime:
- plugins/MyPluginDirectory
filesToOnlyUploadOnServerStop:
- plugins/MyPluginDirectory/my_big_database.db
filesToNotSync:
- plugins/bStats
ticksPerInactiveEntityTracking: 1
interServerCompressionThreshold: 1024
interServerConsolidationDelay: 2

**Comment by dandanlong123** [comment]
# This is the main configuration file for MultiPaper.
# There's quite alot to configure. Read the docs for more information.
#
# Docs: https://github.com/PureGero/MultiPaper/blob/main/MULTIPAPER_YAML.md 

bungeecordName: server01171
multipaperMasterAddress: 45.125.45.227:8051
syncJsonFiles: true
advertiseToBuiltInProxy: true
syncScoreboards: true
logFileSyncing: true
filesToSyncOnStartup:
- myconfigfile.yml
- plugins/MyPlugin.jar
filesToSyncInRealTime:
- plugins/MyPluginDirectory
filesToOnlyUploadOnServerStop:
- plugins/MyPluginDirectory/my_big_database.db
filesToNotSync:
- plugins/bStats
ticksPerInactiveEntityTracking: 1
interServerCompressionThreshold: 1024
interServerConsolidationDelay: 2

**Comment by dandanlong123** [comment]
[Uploading 2022-04-17-4.log…]()

**Comment by dandanlong123** [comment]
[Uploading 2022-04-17-4.log…]()

**Comment by xymb-endcrystalme** [comment]
`45.125.45.227:8051`

If you do `nmap 45.125.45.227 -p 8051` does it work? My nmap says it's filtered, did you configure your firewall correctly?

**Comment by xymb-endcrystalme** [comment]
Oh, ok! I suspect that your P2P can't connect.

MultiPapers don't only communicate with Master, they also communicate among themselves.

So if you're using some stranger, far away configuration across the internet, bind them to WireGuard VPN.
Or bind them to an internet port and make sure your firewall allows every MP to connect to every other MP.

Basically make sure all MultiPapers can connect to each other. And I don't know if `localhost:8051` doesn't screw up P2P - try `45.125.45.227:8051` on both hosts.

**Comment by dandanlong123** [comment]
The ports can pass normally and play games normally. The firewall is also closed. Players can enter the service normally, but they can't link the two services

**Comment by dandanlong123** [comment]
There is a sign that the two services can be connected whoever opens them first, but the later ones can't connect to each other anyway and will always be rejected

**Comment by dandanlong123** [comment]
In other words, both MPs can be linked to the master controller, but the two MPs cannot be linked to each other

**Comment by dandanlong123** [comment]
Is there any good solution

**Comment by xymb-endcrystalme** [comment]
Set up WireGuard or OpenVPN and bind all MP's and Master to the VPN private network.
