### ISSUE TITLE
`useLocalPlayerCountForServerIsFullKick` should be true by default

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#158]
Everyone I saw configuring MP was confused by the player limit being global.
I also assumed it was local by default.

So I think that "true" as default is a better choice.

**Comment by PureGero** [comment]
It's for backwards compatibility. If you upgrade your server to the latest version and this value suddenly becomes true without warning, it's gonna be really annoying

**Comment by xymb-endcrystalme** [comment]
I agree. :+1:
