### ISSUE TITLE
Feature Request: Add option to connect to another MultiPaper server when the one you are on goes down.

### ISSUE THREAD

**Issue by IlluzionzDev** [PureGero/MultiPaper#159]
I think it would be handy if this was an option as at the moment you will just be disconnected with the "Server Closed" message. Ideally, it would connect you to another MultiPaper server if available as a fallback, for a "seamless" transition

**Comment by xymb-endcrystalme** [comment]
That's a feature request to the load balancing plugin you're using in your Velocity/Waterfall.
Unless you're talking about internal proxy? But that should recognize which servers are up or down already.

**Comment by IlluzionzDev** [comment]
Yea I was meaning on the internal proxy, in my testing it doesn't connect you to another server as fallback when the one you are on goes down.

**Comment by IlluzionzDev** [comment]
Yea I was meaning on the internal proxy, in my testing it doesn't connect you to another server as fallback when the one you are on goes down.

**Comment by PureGero** [comment]
The built-in proxy is a basic load balancer, that is not capable of changing the server you're connected to. If you want additional features like this, I recommend looking into using Bungeecord or Velocity. I believe Velocity has the fallback feature when a server closes enabled by default.
