### ISSUE TITLE
1.19 Update

### ISSUE THREAD

**Issue by YTiceice** [PureGero/MultiPaper#195]
Any plans will update to 1.19?

**Comment by Sepera-okeq** [comment]
Hey! I would not recommend you to hurry up so quickly, because even Paper has not made a stable version.

**Comment by Sepera-okeq** [comment]
@YTiceice  The author talked about the 1.19 update, but please wait until there are enough stable versions so that the author can work with Paper 1.19!

**Comment by YTiceice** [comment]
ok, thanks for your reply

**Comment by BasToTheMax** [comment]
There are stable releases now
