### ISSUE TITLE
Can't use /tell command

### ISSUE THREAD

**Issue by YTiceice** [PureGero/MultiPaper#198]
When player use /tell command, they will not receive any messages, even in the same server

**Comment by PureGero** [comment]
/tell is working fine for me. Do you have any plugins overriding /tell ? Can you list your plugins and send a screenshot?

**Comment by YTiceice** [comment]
I use /minecraft:tell is worked, there should be a plugin overriding the /tell command, but I don't know which one
This is my plugins.
![image](https://user-images.githubusercontent.com/87787929/174486891-f6c0c0af-36b7-4dc9-addd-172e5bfd8273.png)

**Comment by YTiceice** [comment]
I don't know why this problem was fixed after restarting several times, sorry for wasting your time
