### ISSUE TITLE
Velocity cannot send player to different node 

### ISSUE THREAD

**Issue by Madscience763** [PureGero/MultiPaper#199]
Using /server and clicking the node you want to connect to returns You are already logged in. 
![image](https://user-images.githubusercontent.com/104371439/174124573-085e2883-8cd0-4366-a4cf-4ac78f0aaa83.png)

**Comment by PureGero** [comment]
This is an issue with Velocity. Velocity tries to connect you to slave-1 while you are still logged into slave-5. Thus, you are not able to connect to slave-1 because you are already logged into the MultiPaper network.

**Comment by PureGero** [comment]
Disconnect the player from the server, wait for the server to save their playerdata, then connect them to the other server.
