### ISSUE TITLE
Cannot Connect with null reason

### ISSUE THREAD

**Issue by Lexivale** [PureGero/MultiPaper#2]
I have try to setup using MultiPaper as a server an using Bungeecord with plugin MultiPaperProxy, all have done with it. but the console from Bungeecord get spamming looks like this : 

```
[03:09:41 INFO]: /*.*.*.*:62110 (null) closed
[03:09:41 INFO]: /*.*.*.*:62119 (null) closed
```

I hope this can be fixed, because player cannot connect to the server using MultiPaper port, and in server list MultiPaper port doesnt seem look like on.

Thanks,

**Comment by PureGero** [comment]
The players connect to your Bungeecord like a normal minecraft server. The MultiPaper servers themselves are what connect to the MultiPaperProxy port, not the players.

**Comment by Lexivale** [comment]
yes, that was i did. but only loading screen what i get. Have you try using 1.17.1 build using it? and this is my setup :

player -> bungeecord -> MultiPaperProxy-Plugin -> MultiPaperServer-1 / MultiPaperServer-2

I can send my IP in my server development, so you can check what i have missed.

and, Is there any contact i can get for better support? i really like MultiPaper and hope its keep on

**Comment by PureGero** [comment]
The bungeecord connects to the MultiPaperServers. The MultiPaperServers themselves connect to MultiPaperProxy-Plugin.

Here's an example of the requirements for a MultiPaper setup:

### Bungeecord
Running BungeeCord/Waterfall/etc
- config.yml
```
servers:
  multipaperserver1:
    address: localhost:25566
  multipaperserver2:
    address: localhost:25567
```
- plugins/multipaper-master-1.0.0.jar
- plugins/MultiPaperProxy/config.yml
```
port: 25000
```

### MultiPaperServer-1
Running MultiPaper-1.17.1-R0.1-SNAPSHOT.jar
- server.properties
```
server-port=25566
```
- multipaperserver.txt
```
localhost:25000
```
- bungeecordname.txt
```
multipaperserver1
```

### MultiPaperServer-2
Running MultiPaper-1.17.1-R0.1-SNAPSHOT.jar
- server.properties
```
server-port=25567
```
- multipaperserver.txt
```
localhost:25000
```
- bungeecordname.txt
```
multipaperserver2
```

**Comment by Lexivale** [comment]
i will show my config, i can join server but player doesnt split in 2 server

Waterfall config.yml - https://hastebin.com/ukurixukax.yaml
MultiPaperProxy config.yml https://hastebin.com/hekakixube.yaml
multipaperserver.txt - https://hastebin.com/azaqiguwop.apache
bungeecordname.txt sv1 - https://hastebin.com/piyuwasuya
bungeecordname.txt sv2 - https://hastebin.com/dosaqawage

**Comment by PureGero** [comment]
The proxy log snippet is missing the information showing that Lexivale disconnected from sv2 such as:
```
07:39:02 [INFO] [Lexivale] <-> DownstreamBridge <-> [sv2] has disconnected
```

Perhaps Waterfall is messing with the server changing process, want to try BungeeCord? I've never tried Waterfall with the latest versions of MultiPaper

**Comment by Lexivale** [comment]
i have done try change to Bungeecord, still same... player doesnt split to another server... everyone join will send to 1 server only

**Comment by PureGero** [comment]
Would you be able to send your full proxy log?

**Comment by Lexivale** [comment]
of course,

https://hastebin.com/urayayetub.sql

**Comment by PureGero** [comment]
It looks like it's working fine. LXVL2665 is on sv1, Lexivale tries to join sv2, but then MultiPaper sends Lexivale to sv1.

MultiPaper puts players on the same server if they're close together (usually if they're within 5x the render distance of eachother). This ensures that the chunks are only loaded on one server at a time.

Try sending one of the players thousands of blocks out and see if it then works.

**Comment by Lexivale** [comment]
omg its works! thanks!

i have a little bit question with scenario

sv1 = server 1
sv2 = server 2
p1 = player 1
p2 = player 2

When p1 join first time it send to sv1 and when p2 join with different chunk it send to sv2 and then when p2 try to closest to p1 chunk p2 will send to sv1 same as p1 server. but when p2 try to go far away p2 doesnt send to sv2. is it weird?

**Comment by PureGero** [comment]
MultiPaper tries to minimise the number of times you change server, so it won't change servers when you go too far away. If you log out and log back in, it'll put you onto the least laggy server. Also if you teleport using a command like /home or /tpa, and the server you're on is laggy, it'll change you to a less laggy server.

You can view the lagginess of each server using /servers
