### ISSUE TITLE
Conduit Power not synced

### ISSUE THREAD

**Issue by ATMmachin3** [PureGero/MultiPaper#43]
1. A player of from a shard not in charge of the conduit enters the range of the conduit and does not receive the effect, yes this is under water, a player from the shard in charge can be a recipient of the effect.

2. A conduit can attack hostile entities such as zombies and drowned when they are within range, for a base I put a zombie in the conduit chamber, it was killed. I then went into the next chunk owned by another Shard and spawned a zombie, this zombie did not die. To ensure it wasn't a wall in the way, I then went back into the chunk with the conduit and mirrored my setup with the last zombie, I then summoned the zombie in the same place (relative) and it was killed.

I have these set up on your test server if you want to check them out to see if there was a flaw in my test.

**Comment by PureGero** [comment]
Fixed with 30c8cac
