### ISSUE TITLE
Text on signs fails to show/register when written in foreign chunk

### ISSUE THREAD

**Issue by ATMmachin3** [PureGero/MultiPaper#44]
When placing a sign and entering text in your own shard's chunk you can view the text which was written, it does not however show for members of other shards. If you go to a foreign chunk and write on a sign, the text will flash briefly then disappear, when you copy with NBT, the NBT does register and can be placed showing original text, but is not viewable to those from foreign shards. This was explained horribly, @ me on discord if you have any questions

**Comment by PureGero** [comment]
Entering text on a foreign shard's chunk has been fixed with da34e51
Entering text on your own shard's chunk has been fixed with 89b4878
