### ISSUE TITLE
Dripstone misbehaves

### ISSUE THREAD

**Issue by ATMmachin3** [PureGero/MultiPaper#46]
When a dripstone is dropped, it is visually and physically no longer there on the home shard, but foreign shards still see dripstone and can interact with it, even if no physics apply. I have not yet replicated this but am in the process of doing so

edit: Unable to replicate
edit 2: able to replicate by breaking block above instead of actual dripstone
edit 3: Ghost blocks are left on client of foreign shard
edit 4: If foreign client breaks block everything behaves

**Comment by PureGero** [comment]
Can't replicate, I might've changed something with how physics work since, so it might be fixed.

Try it again, and if you can replicate, give me detailed steps on how to reproduce

**Comment by ATMmachin3** [comment]
https://youtu.be/Xv07NJ3IbyE
Method for reproduction and showing consequences

**Comment by PureGero** [comment]
I think fda4400 fixes it, feel free to reopen this issue if it still occurs
