### ISSUE TITLE
Proxy routing player limit consideration

### ISSUE THREAD

**Issue by RigidOfficial** [PureGero/MultiPaper#80]
Make the server selector use the next-best server if the best one is full.

**Comment by PureGero** [comment]
With the current way the players are synced, when one server is full, they will all be full. The player count on each server is synced such that if server1 has 5 players online, server2 will also think that it has 5 players online, even if it actually has 0. Thus, if you set a player limit of 5, both server1 and server2 will be full, even though server2 has zero players online.

**Comment by RigidOfficial** [comment]
I see, the current balance system works well on a large scale then and that's satisfactory. I'll close this as it isn't really necessary.
