### ISSUE TITLE
Dropped items don't render a fair amount of the time

### ISSUE THREAD

**Issue by PureGero** [PureGero/MultiPaper#86]
If a player drops an item, it will occasionally not render for them. The item exists in the world, and can be picked up by the player, but it can't be seen by the player.

**Comment by PureGero** [comment]
Can reproduce on Pufferfish, thus not a MultiPaper issue. Only appears to occur with high ping.

**Comment by Paul19988** [comment]
I've personally seen this error occur on Vanilla servers as well, seems to be a client render issue afaik.

**Comment by PureGero** [comment]
Can confirm, am able to reproduce using Vanilla. How annoying, I feel defeated. Definitely seems to be a client issue, I can't find anything wrong with the packets being sent.
