### ISSUE TITLE
Add Velocity plugin

### ISSUE THREAD

**Issue by PureGero** [PureGero/MultiPaper#91]
Make MultiPaper-Master able to be run as a Velocity plugin

**Comment by PureGero** [comment]
Until this is resolved: Run MultiPaper-Master as a standalone application, and use the [bhopahk/VelocityLoadBalancer](https://github.com/bhopahk/VelocityLoadBalancer) plugin to evenly distribute players across your servers.

**Comment by dalicor** [comment]
Necessary!!!
