### ISSUE TITLE
Feature request: Add an option to disable syncing ops.json, etc..

### ISSUE THREAD

**Issue by TypicalShavonne** [PureGero/MultiPaper#93]
please add an option to disable syncing  ``banned-players.json, banned-ips.json, ops.json, whitelist.json``

**Comment by PureGero** [comment]
I'm interested in the use case for not syncing these.

**Comment by TypicalShavonne** [comment]
1. Big server usually have their own ban managing system
2. Who the hell using OP status anymore, permission plugins are better ^^
It only for small server like SMPs, people playing with friends, etc. For large-scale, big server, isnt necessary
