### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by TypicalShavonne** [PureGero/MultiPaper#95]
https://cljdoc.org/d/com.github.puregero/multipaper-api/1.18-R0.1-SNAPSHOT isnt working

**Comment by PureGero** [comment]
What's a cljdoc.org? I don't think MultiPaper uses that

**Comment by TypicalShavonne** [comment]
![image](https://user-images.githubusercontent.com/53472591/152513015-b5c5af61-9331-4656-9257-c5ed85b9edb9.png)
well, its here :)

**Comment by TypicalShavonne** [comment]
![image](https://user-images.githubusercontent.com/53472591/152513087-46d90b0a-0107-4941-9581-65fde6c0906e.png)

**Comment by PureGero** [comment]
Yeah, just don't click that button. That page is intended for seeing the Maven and Gradle information. The cljdoc button is out of my control and can't be removed it seems.
